name: telkom_career
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  datetime_picker_formfield_new: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  bottom_navigation_bar: ^1.0.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.17
  top_snackbar_flutter: ^2.1.1
  alert_dialog: ^1.0.1
  image_picker: ^0.8.7
  flash: ^2.0.5+1
  velocity_x: ^3.6.0
  file_picker: ^5.2.8
  intl: ^0.17.0
  http_parser: ^4.0.2
  path_provider: ^2.0.15
  readmore: ^2.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.2.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/images/ImageLogin.png
    # - assets/images/illus_email_sent.png
    # - assets/images/illus_login.png
    # - assets/images/illus_u_password.png
    # - assets/images/imagesuperindo.png
    # - assets/images/image1.png
    # - assets/images/image887.png
    # - assets/images/image4.png
    # - assets/images/image5.png
    # - assets/images/image6.png
    # - assets/images/image7.png
    # - assets/images/image8.png
    # - assets/images/image888.png
    # - assets/images/image889.png
    # - assets/images/image891.png
    # - assets/images/image892.png
    # - assets/images/image890.png
    # - assets/images/image895.png
    # - assets/images/avatar.png
    # - assets/images/ellipse.png
    # - assets/images/illus_portfolio.png

    - assets/icons/
    # - assets/icons/beranda.png
    # - assets/icons/notif.png
    # - assets/icons/pekerjaan.png
    # - assets/icons/pesan.png
    # - assets/icons/profil.png
    # - assets/icons/kegiatan.png
    # - assets/icons/setting.png
    # - assets/icons/icon_edit.png
    # - assets/icons/more.png
    # - assets/icons/camera.png
    # - assets/icons/galery.png
    # - assets/icons/trash.png
    # - assets/icons/back.png
    # - assets/icons/search.png
    # - assets/icons/toggle-on.png
    # - assets/icons/toggle-off.png
    # - assets/icons/calendar.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_Regular.ttf
        - asset: assets/fonts/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter_bold.ttf
          weight: 700 
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
